export default {
  menFly: {
    division: 'Men\'s Flyweight',
    champ: { name: 'Henry Cejudo' },
    rankings: [
      { name: 'Jussier Formiga' },
      { name: 'Joseph Benavidez' },
      { name: 'Ray Borg' },
      { name: 'Deiveson Figueiredo' },
      { name: 'John Moraga' },
      { name: 'Wilson Reis' },
      { name: 'Alexandre Pantoja' },
      { name: 'Dustin Ortiz' },
      { name: 'Alex Perez' },
      { name: 'Tim Elliott' },
      { name: 'Magomed Bibulatov' },
      { name: 'Said Nurmagomedov' },
      { name: 'Ryan Benoit' },
      { name: 'Eric Shelton' },
      { name: 'Matt Schnell' },
    ]
  },
  menBantam: {
    division: 'Men\'s Bantamweight',
    champ: { name: 'TJ Dillashaw' },
    rankings: [
      { name: 'Cody Garbrandt' },
      { name: 'Dominick Cruz' },
      { name: 'Raphael Assuncao' },
      { name: 'Marlon Moraes' },
      { name: 'Jimmie Rivera' },
      { name: 'John Lineker' },
      { name: 'Aljamain Sterling' },
      { name: 'John Dodson' },
      { name: 'Pedro Munhoz' },
      { name: 'Rob Font' },
      { name: 'Cody Stamann' },
      { name: 'Alejandro Perez' },
      { name: 'Thomas Almeida' },
      { name: 'Petr Yan' },
      { name: 'Rani Yahya' },
    ]
  },
  menFeather: {
    division: 'Men\'s Featherweight',
    champ: { name: 'Max Holloway' },
    rankings: [
      { name: 'Brian Ortega' },
      { name: 'Jose Aldo' },
      { name: 'Frankie Edgar' },
      { name: 'Alexander Volkanovski' },
      { name: 'Renato Moicano' },
      { name: 'Jeremy Stephens' },
      { name: 'Cub Swanson' },
      { name: 'Chad Mendes' },
      { name: 'Mirsad Bektic' },
      { name: 'Josh Emmett' },
      { name: 'Ricardo Lamas' },
      { name: 'Yair Rodriguez' },
      { name: 'Chan Sung Jung' },
      { name: 'Zabit Magomedsharipov' },
      { name: 'Darren Elkins' },
    ]
  },
  light: {
    division: 'Lightweight',
    champ: { name: 'Khabib Nurmagomedov' },
    rankings: [
      { name: 'Tony Ferguson' },
      { name: 'Conor McGregor' },
      { name: 'Dustin Poirier' },
      { name: 'Al Iaquinta' },
      { name: 'Kevin Lee' },
      { name: 'Edson Barboza' },
      { name: 'Justin Gaethje' },
      { name: 'Anthony Pettis' },
      { name: 'James Vick' },
      { name: 'Nate Diaz' },
      { name: 'Alexander Hernandez' },
      { name: 'Francisco Trinaldo' },
      { name: 'Dan Hooker' },
      { name: 'Paul Felder' },
      { name: 'Islam Makhachev' },
      { name: 'Gregor Gillespie' },
    ]
  },
  welter: {
    division: 'Welterweight',
    champ: { name: 'Tyron Woodley' },
    rankings: [
      { name: 'Colby Covington' },
      { name: 'Kamaru Usman' },
      { name: 'Darren Till' },
      { name: 'Stephen Thompson' },
      { name: 'Rafael Dos Anjos' },
      { name: 'Robbie Lawler' },
      { name: 'Santiago Ponzinibbio' },
      { name: 'Demian Maia' },
      { name: 'Jorge Masvidal' },
      { name: 'Leon Edwards' },
      { name: 'Neil Magny' },
      { name: 'Gunnar Nelson' },
      { name: 'Donald Cerrone' },
      { name: 'Elizeu Zaleski dos Santos' },
      { name: 'Alex Oliveira' },
    ]
  },
  middle: {
    division: 'Middleweight',
    champ: { name: 'Robert Whittaker' },
    rankings: [
      { name: 'Yoel Romero' },
      { name: 'Luke Rockhold' },
      { name: 'Jacare Souza' },
      { name: 'Kelvin Gastelum' },
      { name: 'Chris Weidman' },
      { name: 'Israel Adesanya' },
      { name: 'Paulo Costa' },
      { name: 'Derek Brunson' },
      { name: 'Jared Cannonier' },
      { name: 'Brad Tavares' },
      { name: 'David Branch' },
      { name: 'Antonio Carlos Junior' },
      { name: 'Uriah Hall' },
      { name: 'Elias Theodorou' },
      { name: 'Thiago Santos' },
    ]
  },
  lightHeavy: {
    division: 'Light Heavyweight',
    champ: { name: 'Jon Jones' },
    rankings: [
      { name: 'Daniel Cormier' },
      { name: 'Alexander Gustafsson' },
      { name: 'Anthony Smith' },
      { name: 'Jan Blachowicz' },
      { name: 'Volkan Oezdemir' },
      { name: 'Corey Anderson' },
      { name: 'Thiago Santos' },
      { name: 'Dominick Reyes' },
      { name: 'Ilir Latifi' },
      { name: 'Jimi Manuwa' },
      { name: 'Ovince Saint Preux' },
      { name: 'Glover Teixeira' },
      { name: 'Mauricio Rua' },
      { name: 'Misha Cirkunov' },
      { name: 'Nikita Krylov' },
    ]
  },
  heavy: {
    division: 'Heavyweight',
    champ: { name: 'Daniel Cormier' },
    rankings: [
      { name: 'Stipe Miocic' },
      { name: 'Derrick Lewis' },
      { name: 'Francis Ngannou' },
      { name: 'Curtis Blaydes' },
      { name: 'Alexander Volkov' },
      { name: 'Alistair Overeem' },
      { name: 'Junior Dos Santos' },
      { name: 'Aleksei Oleinik' },
      { name: 'Marcin Tybura' },
      { name: 'Justin Willis' },
      { name: 'Tai Tuivasa' },
      { name: 'Shamil Abdurakhimov' },
      { name: 'Walt Harris' },
      { name: 'Andrei Arlovski' },
      { name: 'Stefan Struve' },
    ]
  },
  straw: {
    division: 'Strawweight',
    champ: { name: 'Rose Namajunas' },
    rankings: [
      { name: 'Jessica Andrade' },
      { name: 'Joanna Jedrzejczyk' },
      { name: 'Nina Ansaroff' },
      { name: 'Tatiana Suarez' },
      { name: 'Claudia Gadelha' },
      { name: 'Karolina Kowalkiewicz' },
      { name: 'Tecia Torres' },
      { name: 'Michelle Waterson' },
      { name: 'Carla Esparza' },
      { name: 'Felice Herrig' },
      { name: 'Cortney Casey' },
      { name: 'Cynthia Calvillo' },
      { name: 'Alexa Grasso' },
      { name: 'Randa Markos' },
      { name: 'Mackenzie Dern' },
    ]
  },
  womenFly: {
    division: 'Women\'s Flyweight',
    champ: { name: 'Valentina Shevchenko' },
    rankings: [
      { name: 'Jessica Eye' },
      { name: 'Sijara Eubanks' },
      { name: 'Katlyn Chookagian' },
      { name: 'Joanna Jedrzejczyk' },
      { name: 'Alexis Davis' },
      { name: 'Liz Carmouche' },
      { name: 'Roxanne Modafferi' },
      { name: 'Lauren Murphy' },
      { name: 'Jessica-Rose Clark' },
      { name: 'Joanne Calderwood' },
      { name: 'Jennifer Maia' },
      { name: 'Ashlee Evans-Smith' },
      { name: 'Mara Romero Borella' },
      { name: 'Andrea Lee' },
      { name: 'Montana De La Rosa' },
    ]
  },
  womenBantam: {
    division: 'Women\'s Bantamweight',
    champ: { name: 'Amanda Nunes' },
    rankings: [
      { name: 'Germaine de Randamie' },
      { name: 'Holly Holm' },
      { name: 'Ketlen Vieira' },
      { name: 'Raquel Pennington' },
      { name: 'Cat Zingano' },
      { name: 'Marion Reneau' },
      { name: 'Aspen Ladd' },
      { name: 'Sara McMann' },
      { name: 'Yana Kunitskaya' },
      { name: 'Irene Aldana' },
      { name: 'Tonya Evinger' },
      { name: 'Bethe Correia' },
      { name: 'Lina Lansberg' },
      { name: 'Lucie Pudilova' },
      { name: 'Talita Bernardo' },
    ]
  },
  womenFeather: {
    division: 'Women\'s Featherweight',
    champ: { name: 'Cris Cyborg' },
    rankings: [
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
      { name: '' },
    ]
  }
}
